// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX6dL1-dOpIJ7VRgQxLCC6s__ZaOOp7Ao',
    appId: '1:902078062128:web:08110c485c0066dcfa17f5',
    messagingSenderId: '902078062128',
    projectId: 'parkez-b46d5',
    authDomain: 'parkez-b46d5.firebaseapp.com',
    databaseURL: 'https://parkez-b46d5-default-rtdb.firebaseio.com',
    storageBucket: 'parkez-b46d5.appspot.com',
    measurementId: 'G-83G6F95C6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRIEm4N0555LJtm7odHwMb98PokTS00Y',
    appId: '1:902078062128:android:e3238023224a0f77fa17f5',
    messagingSenderId: '902078062128',
    projectId: 'parkez-b46d5',
    databaseURL: 'https://parkez-b46d5-default-rtdb.firebaseio.com',
    storageBucket: 'parkez-b46d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqDPgdjssl-AtzGJeZszq3A5-RF7BrTw',
    appId: '1:902078062128:ios:2e834c42cf6aa9a9fa17f5',
    messagingSenderId: '902078062128',
    projectId: 'parkez-b46d5',
    databaseURL: 'https://parkez-b46d5-default-rtdb.firebaseio.com',
    storageBucket: 'parkez-b46d5.appspot.com',
    iosBundleId: 'com.example.parkez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqDPgdjssl-AtzGJeZszq3A5-RF7BrTw',
    appId: '1:902078062128:ios:f0128d3cfe743f88fa17f5',
    messagingSenderId: '902078062128',
    projectId: 'parkez-b46d5',
    databaseURL: 'https://parkez-b46d5-default-rtdb.firebaseio.com',
    storageBucket: 'parkez-b46d5.appspot.com',
    iosBundleId: 'com.example.parkez.RunnerTests',
  );
}
